### ISSUE TITLE
Debugger for Edge crash when refresh/restart

### ISSUE THREAD

**Issue by E5TE** [microsoft/vscode-edge-debug2#161] opened 2019-10-22 15:47 UTC
- VS Code Version:1.39.2

- Log file (set `"trace": true` in launch config):

*For some reason I cannot upload the log file...I am coping & pasting the error*

``` Error processing "restart": Error
    at Client.processMessage (c:\Users\Lab\.vscode\extensions\msjsdiag.debugger-for-edge-1.0.12\node_modules\noice-json-rpc\lib\noice-json-rpc.js:66:36)
    at LoggingSocket.Client.socket.on (c:\Users\Lab\.vscode\extensions\msjsdiag.debugger-for-edge-1.0.12\node_modules\noice-json-rpc\lib\noice-json-rpc.js:42:48)
    at LoggingSocket.emit (events.js:187:15)
    at Receiver.receiverOnMessage (c:\Users\Lab\.vscode\extensions\msjsdiag.debugger-for-edge-1.0.12\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (c:\Users\Lab\.vscode\extensions\msjsdiag.debugger-for-edge-1.0.12\node_modules\ws\lib\receiver.js:422:14)
    at Receiver.getData (c:\Users\Lab\.vscode\extensions\msjsdiag.debugger-for-edge-1.0.12\node_modules\ws\lib\receiver.js:352:17)
    at Receiver.startLoop (c:\Users\Lab\.vscode\extensions\msjsdiag.debugger-for-edge-1.0.12\node_modules\ws\lib\receiver.js:138:22)
    at Receiver._write (c:\Users\Lab\.vscode\extensions\msjsdiag.debugger-for-edge-1.0.12\node_modules\ws\lib\receiver.js:74:10)
    at doWrite (_stream_writable.js:410:12)
```
### Description:
* **Debugger for Edge crashes after refreshing/restarting**

### Steps to reproduce:

* From Visual code, press at Launch Debugger for Edge
* Once you see the page displaying and the debugger control panel at the top-center of the screen press 'Restart' at the debugger control panel (the green button)

**Comment by rakatyal** [comment] 2019-10-28 21:15
This is a duplicate of https://github.com/microsoft/vscode-edge-debug2/issues/69. Please comment on the original issue for support on fixing it.

**Closed by rakatyal** 2019-10-28 21:15 UTC
Labels: duplicate
